# This example is specific for Ubuntu, run the following commands before starting the compose:
# # install required kernel modules
# apt install linux-modules-extra-`uname -r`
# modprobe binder_linux devices="binder,hwbinder,vndbinder"
# # optional module (removed since 5.18)
# modprobe ashmem_linux
#
# You may find the Redroid deploy instructions for other distros here: https://github.com/remote-android/redroid-doc/tree/master/deploy
#
# The ./init.d folder should contain the "setup.sh" and "reset.sh" scripts

services:
  redroid:
    privileged: true
    ports:
      - 5555:5555 # No need to expose this, but it's useful for debugging purposes
    container_name: redroid14
    image: redroid/redroid:14.0.0-latest
  droidground:
    build: ..
    image: secforce/droidground:0.1.0
    container_name: droidground
    restart: on-failure
    ports:
      - 4242:4242
    env_file:
      - ../.env
    volumes:
      - ./init.d:/init.d
    environment:
      - DG_DEVICE_TYPE=network
      - DG_DEVICE_HOST=redroid
      - DG_DEVICE_PORT=5555
      - DG_INIT_SCRIPTS_FOLDER=/init.d
