services:
  docker-android:
    image: halimqarroum/docker-android:api-33
    devices:
      - /dev/kvm
    ports:
      - 5555:5555 # No need to expose this, but it's useful for debugging purposes
    container_name: docker-android
  droidground:
    build: ..
    image: secforce/droidground:0.1.0
    container_name: droidground
    restart: on-failure
    ports:
      - 4242:4242
    env_file:
      - ../.env
    environment:
      - DG_DEVICE_TYPE=network
      - DG_DEVICE_HOST=docker-android
      - DG_DEVICE_PORT=5555
