# The ./init.d folder should contain the "setup.sh" and "reset.sh" scripts

services:
  android-device:
    image: halimqarroum/docker-android:api-33
    devices:
      - /dev/kvm
    ports:
      - 5555:5555 # No need to expose this, but it's useful for debugging purposes
    container_name: docker-android
  droidground:
    build: ../../..
    container_name: droidground
    restart: unless-stopped
    ports:
      - 4242:4242
    volumes:
      - ./init.d:/init.d
    env_file:
      - hidden-activity.env
