# This example is specific for Debian, run the following commands before starting the compose:
# modprobe binder_linux devices=binder1,binder2,binder3,binder4,binder5,binder6
# chmod 666 /dev/binder*
#
# You may find the Redroid deploy instructions for other distros here: https://github.com/remote-android/redroid-doc/tree/master/deploy
#
# The ./init.d folder should contain the "setup.sh" and "reset.sh" scripts

services:
  android-device:
    privileged: true
    volumes:
      - /dev/binder1:/dev/binder
      - /dev/binder2:/dev/hwbinder
      - /dev/binder3:/dev/vndbinder
    ports:
      - 5555:5555 # No need to expose this, but it's useful for debugging purposes
    container_name: redroid
    image: redroid/redroid:14.0.0-latest
    command: ["ro.debuggable=0", "ro.boot.verifiedbootstate=orange"]
  droidground:
    build: ../../..
    container_name: droidground
    restart: unless-stopped
    ports:
      - 4242:4242
    volumes:
      - ./init.d:/init.d
    env_file:
      - hidden-activity.env
