# This example is specific for Ubuntu, run the following commands before starting the compose:
# # install required kernel modules
# apt install linux-modules-extra-`uname -r`
# modprobe binder_linux devices="binder,hwbinder,vndbinder"
# # optional module (removed since 5.18)
# modprobe ashmem_linux
#
# You may find the Redroid deploy instructions for other distros here: https://github.com/remote-android/redroid-doc/tree/master/deploy
#
# The ./init.d folder should contain the "setup.sh" and "reset.sh" scripts

services:
  android-device:
    privileged: true
    ports:
      - 5555:5555 # No need to expose this, but it's useful for debugging purposes
    container_name: redroid
    image: redroid/redroid:14.0.0-latest
    command: ["ro.debuggable=0", "ro.boot.verifiedbootstate=orange"]
  droidground:
    build: ../../..
    container_name: droidground
    restart: unless-stopped
    ports:
      - 4242:4242
    volumes:
      - ./init.d:/init.d
    env_file:
      - hidden-activity.env
