# The ./init.d folder should contain the "setup.sh" and "reset.sh" scripts

services:
  docker-android:
    image: halimqarroum/docker-android:api-33
    devices:
      - /dev/kvm
    container_name: docker-android-${INSTANCE_ID}
    networks:
      - droidground
  droidground:
    build: ../..
    container_name: droidground-${INSTANCE_ID}
    restart: unless-stopped
    volumes:
      - ./init.d:/init.d
    environment:
      - DROIDGROUND_BASE_PATH=/${INSTANCE_ID}
      - DROIDGROUND_APP_PACKAGE_NAME=com.droidground.hiddenactivity
      - DROIDGROUND_ADB_HOST=localhost
      - DROIDGROUND_ADB_PORT=5037
      - DROIDGROUND_DEVICE_TYPE=network
      - DROIDGROUND_DEVICE_HOST=docker-android-${INSTANCE_ID}
      - DROIDGROUND_DEVICE_PORT=5555
      - DROIDGROUND_INIT_SCRIPTS_FOLDER=/init.d
      - DROIDGROUND_HOST=0.0.0.0
      - DROIDGROUND_PORT=4242
      - DROIDGROUND_SHUTDOWN_DISABLED=true
      - DROIDGROUND_APP_MANAGER_DISABLED=true
      - DROIDGROUND_FRIDA_DISABLED=true
      - DROIDGROUND_START_RECEIVER_DISABLED=true
      - DROIDGROUND_START_SERVICE_DISABLED=true
      - DROIDGROUND_TERMINAL_DISABLED=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${INSTANCE_ID}.rule=PathPrefix(`/${INSTANCE_ID}`)"
      - "traefik.http.services.${INSTANCE_ID}.loadbalancer.server.port=4242"
    networks:
      - droidground

networks:
  droidground:
    external: true
